# Generated by Django 5.2.6 on 2025-09-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
