# Generated by Django 5.2.8 on 2025-11-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('past_paper', 'Past Paper'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('book', 'Book'), ('notes', 'Notes'), ('other', 'Other')], max_length=20),
        ),
    ]
