# Generated by Django 5.2.6 on 2025-09-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='ig_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='li_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
