# Generated by Django 5.2.6 on 2025-09-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_ig_username_journal_li_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
