# Generated by Django 5.2.8 on 2025-12-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_rename_is_featured_journal_is_featured_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
