# Generated by Django 5.2.8 on 2025-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_alter_journal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='cover_image_url',
        ),
        migrations.AlterField(
            model_name='journal',
            name='batch',
            field=models.CharField(blank=True, choices=[('2020-24', '2020-24'), ('2021-25', '2021-25'), ('2022-26', '2022-26'), ('2023-27', '2023-27'), ('2024-28', '2024-28'), ('2025-29', '2025-29'), ('2026-30', '2026-30'), ('2027-31', '2027-31')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'BS CS'), ('SE', 'BS SE'), ('AI', 'BS AI'), ('DS', 'BS Data Science'), ('Cyber', 'BS CyberSecurity'), ('BBA', 'BBA'), ('AF', 'BS Accounting'), ('Economics', 'BS Economics'), ('Social', 'BS Social Sciences'), ('English', 'BS English'), ('Psych', 'BS Psychology'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tags',
            field=models.CharField(blank=True, choices=[('technology', 'Tech'), ('career', 'Career'), ('productivity', 'Productivity'), ('featured', 'Featured')], max_length=200, null=True),
        ),
    ]
