# Generated by Django 5.2.8 on 2025-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_remove_journal_cover_image_url_alter_journal_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'BS CS'), ('SE', 'BS SE'), ('AI', 'BS AI'), ('DS', 'BS Data Science'), ('CyberSecurity', 'BS CyberSecurity'), ('BBA', 'BBA'), ('Accounting', 'BS Accounting'), ('Economics', 'BS Economics'), ('Social Sciences', 'BS Social Sciences'), ('English', 'BS English'), ('Psychology', 'BS Psychology'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
