# Generated by Django 5.2.6 on 2025-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journal_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
