# Generated by Django 5.2.8 on 2025-11-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_journal_cover_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='is_featured',
            new_name='is_featured_homepage',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='ig_username',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='li_username',
        ),
        migrations.AlterField(
            model_name='journal',
            name='batch',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('BBA', 'Business Administration'), ('AF', 'Accounting Finance'), ('Psych', 'Psychology'), ('Eng', 'English'), ('AI', 'Artificial Intelligence'), ('SE', 'Software Engineering'), ('DS', 'Data Science'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
