# Generated by Django 5.2.6 on 2025-09-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('past_paper', 'Past Paper'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('book', 'Book'), ('notes', 'Note'), ('other', 'Other')], max_length=20),
        ),
    ]
